# Setup environment for Docker
language: generic
notifications:
  email: false

# The test script for each build
script: |
    TRAVIS_TAG=$(echo $TRAVIS_TAG | cut -d v -f 2)
    echo "Building $DOCKER_IMG:latest"
    docker build -t $DOCKER_IMG:latest .;
    if [ $? != 0 ]; then
      echo "Failed to build Docker image"
      exit 1
    fi
    if [ $TRAVIS_SECURE_ENV_VARS == true ] && [ -n "$TRAVIS_TAG" ]; then
      echo "New tag $TRAVIS_TAG. Push image to Dockerhub"
      echo $DOCKERHUB_PASSWD | docker login --username $DOCKERHUB_USER --password-stdin
      docker tag $DOCKER_IMG:latest $DOCKER_IMAGE:$TRAVIS_TAG
      docker push $DOCKER_IMG:latest
      docker push $DOCKER_IMG:$TRAVIS_TAG
    fi
env:
  global:
    - DOCKER_IMG=niclabs/bot
